In [2]:
using Pkg
Pkg.add("DataFrames")
Pkg.add("PyPlot") #if you haven't yet
Pkg.add("StatsPlots") # using it for hitogram and all the basic things already in Pandas
Pkg.add("ScikitLearn") #case sensitive and wont be using it rn in this notebook


    Updating registry at `C:\Users\Nihal\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
  No Changes to `C:\Users\Nihal\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\Nihal\.julia\environments\v1.6\Manifest.toml`


In [ ]:
# before we start with dataframe lets review the arrays and basic numpy things we used to do
# Arrays


In [8]:
A = [10,20,30] #vector 

3-element Vector{Int64}:
 10
 20
 30

In [12]:
# we use random for creating some matrices
using Random 
rand(3,4) #= (row, columns)


3×4 Matrix{Float64}:
 0.620189  0.935652  0.156193  0.0982893
 0.165794  0.165596  0.429152  0.246788
 0.819437  0.673186  0.334784  0.0868025

In [26]:
# basic numpy counterparts for common matrices 
A = ones(3,4 ) #by default it will be float
A1 =map(x-> trunc(Int,x), A) # a small trick to convert it into Int
#best thing in broadcasting is this @. macro https://stackoverflow.com/questions/56137218/what-is-julia-equivalent-of-numpys-where-function

3×4 Matrix{Int64}:
 1  1  1  1
 1  1  1  1
 1  1  1  1

In [27]:
x = fill(1, (3,2)) # = fill(1.0, 3) #or use this for any type of matrices instead

3×2 Matrix{Int64}:
 1  1
 1  1
 1  1

In [14]:
B = zeros(3,4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [29]:
A = [i*2 for i in 0:10] #if you want to use np.arrange()

11-element Vector{Int64}:
  0
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [31]:
# to use Identity matrice of any size the best Julia offers is 
using LinearAlgebra
I #now julia knows what identity matrix is of any size just use I insteaad of making the size (2,2)

UniformScaling{Bool}
true*I

In [33]:
#julia also has np.random.seed(12) equivalent as
Random.seed!(1234)

MersenneTwister(1234)

In [34]:
rand(2)

2-element Vector{Float64}:
 0.5908446386657102
 0.7667970365022592

In [35]:
rand(2) #we need to initialize the seed everytime we create a new random item

2-element Vector{Float64}:
 0.5662374165061859
 0.4600853424625171

In [36]:
Random.seed!(1234)

MersenneTwister(1234)

In [43]:
c = rand(2,4)

2×4 Matrix{Float64}:
 0.794026  0.200586  0.246837  0.648882
 0.854147  0.298614  0.579672  0.0109059

In [44]:
size(c) #size is the shape in Julia


(2, 4)

In [46]:
A = [1,3 ,4, 5]

4-element Vector{Int64}:
 1
 3
 4
 5

In [47]:
A[2] #indexing starts with 1 instead of zero

3

In [87]:
#negative indices doesnt work in julia unlike python, but we have length as a function
A[end] #end is basically the last index of Array

5

In [50]:
#vector is mutable 
A[2] = 4

4

In [66]:
x = [i for i in 0:9]


10-element Vector{Int64}:
 0
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [67]:
#we can use slicing of arrays 
x[:3] #if nothing is mentioned in the first index it returns the last value
y = x[1:4]

4-element Vector{Int64}:
 0
 1
 2
 3

In [74]:
a = [1 2 3 4; 5 6 7 8; 9 10 11 12]

3×4 Matrix{Int64}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [86]:
a[1:3 , :2] #julia always work columnwise  a[row1 : row 2, Col1 : col2]

3-element Vector{Int64}:
  2
  6
 10

Concatinating array

In [88]:
x = rand(5)
y= rand(3)

3-element Vector{Float64}:
 0.6516642063795697
 0.05664246860321187
 0.8427136165865521

In [94]:
#for concatination we use two function either vcat or hcat 
z= vcat(x,y)

8-element Vector{Float64}:
 0.06642303695533736
 0.9567533636029237
 0.646690981531646
 0.11248587118714015
 0.2760209506672211
 0.6516642063795697
 0.05664246860321187
 0.8427136165865521

In [95]:
?vcat

search: vcat hvcat VecOrMat DenseVecOrMat StridedVecOrMat AbstractVecOrMat



```
vcat(A...)
```

Concatenate along dimension 1.

# Examples

```jldoctest
julia> a = [1 2 3 4 5]
1×5 Matrix{Int64}:
 1  2  3  4  5

julia> b = [6 7 8 9 10; 11 12 13 14 15]
2×5 Matrix{Int64}:
  6   7   8   9  10
 11  12  13  14  15

julia> vcat(a,b)
3×5 Matrix{Int64}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

julia> c = ([1 2 3], [4 5 6])
([1 2 3], [4 5 6])

julia> vcat(c...)
2×3 Matrix{Int64}:
 1  2  3
 4  5  6
```


## DataFrames