In [2]:
using Pkg
Pkg.add("DataFrames")
Pkg.add("PyPlot") #if you haven't yet
Pkg.add("StatsPlots") # using it for hitogram and all the basic things already in Pandas
Pkg.add("ScikitLearn") #case sensitive and wont be using it rn in this notebook


    Updating registry at `C:\Users\Nihal\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
  No Changes to `C:\Users\Nihal\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\Nihal\.julia\environments\v1.6\Manifest.toml`


In [ ]:
# before we start with dataframe lets review the arrays and basic numpy things we used to do
# Arrays


In [8]:
A = [10,20,30] #vector 

3-element Vector{Int64}:
 10
 20
 30

In [12]:
# we use random for creating some matrices
using Random 
rand(3,4) #= (row, columns)


3×4 Matrix{Float64}:
 0.620189  0.935652  0.156193  0.0982893
 0.165794  0.165596  0.429152  0.246788
 0.819437  0.673186  0.334784  0.0868025

In [26]:
# basic numpy counterparts for common matrices 
A = ones(3,4 ) #by default it will be float
A1 =map(x-> trunc(Int,x), A) # a small trick to convert it into Int
#best thing in broadcasting is this @. macro https://stackoverflow.com/questions/56137218/what-is-julia-equivalent-of-numpys-where-function

3×4 Matrix{Int64}:
 1  1  1  1
 1  1  1  1
 1  1  1  1

In [27]:
x = fill(1, (3,2)) # = fill(1.0, 3) #or use this for any type of matrices instead

3×2 Matrix{Int64}:
 1  1
 1  1
 1  1

In [14]:
B = zeros(3,4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [29]:
A = [i*2 for i in 0:10] #if you want to use np.arrange()

11-element Vector{Int64}:
  0
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [31]:
# to use Identity matrice of any size the best Julia offers is 
using LinearAlgebra
I #now julia knows what identity matrix is of any size just use I insteaad of making the size (2,2)

UniformScaling{Bool}
true*I

In [33]:
#julia also has np.random.seed(12) equivalent as
Random.seed!(1234)

MersenneTwister(1234)

In [34]:
rand(2)

2-element Vector{Float64}:
 0.5908446386657102
 0.7667970365022592

In [35]:
rand(2) #we need to initialize the seed everytime we create a new random item

2-element Vector{Float64}:
 0.5662374165061859
 0.4600853424625171

In [36]:
Random.seed!(1234)

MersenneTwister(1234)

In [43]:
c = rand(2,4)

2×4 Matrix{Float64}:
 0.794026  0.200586  0.246837  0.648882
 0.854147  0.298614  0.579672  0.0109059

In [44]:
size(c) #size is the shape in Julia


(2, 4)

In [46]:
A = [1,3 ,4, 5]

4-element Vector{Int64}:
 1
 3
 4
 5

In [47]:
A[2] #indexing starts with 1 instead of zero

3

In [87]:
#negative indices doesnt work in julia unlike python, but we have length as a function
A[end] #end is basically the last index of Array

5

In [50]:
#vector is mutable 
A[2] = 4

4

In [66]:
x = [i for i in 0:9]


10-element Vector{Int64}:
 0
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [67]:
#we can use slicing of arrays 
x[:3] #if nothing is mentioned in the first index it returns the last value
y = x[1:4]

4-element Vector{Int64}:
 0
 1
 2
 3

In [74]:
a = [1 2 3 4; 5 6 7 8; 9 10 11 12]

3×4 Matrix{Int64}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [86]:
a[1:3 , :2] #julia always work columnwise  a[row1 : row 2, Col1 : col2]

3-element Vector{Int64}:
  2
  6
 10

Concatinating array

In [88]:
x = rand(5)
y= rand(3)

3-element Vector{Float64}:
 0.6516642063795697
 0.05664246860321187
 0.8427136165865521

In [94]:
#for concatination we use two function either vcat or hcat 
z= vcat(x,y)

8-element Vector{Float64}:
 0.06642303695533736
 0.9567533636029237
 0.646690981531646
 0.11248587118714015
 0.2760209506672211
 0.6516642063795697
 0.05664246860321187
 0.8427136165865521

In [95]:
?vcat

search: vcat hvcat VecOrMat DenseVecOrMat StridedVecOrMat AbstractVecOrMat



```
vcat(A...)
```

Concatenate along dimension 1.

# Examples

```jldoctest
julia> a = [1 2 3 4 5]
1×5 Matrix{Int64}:
 1  2  3  4  5

julia> b = [6 7 8 9 10; 11 12 13 14 15]
2×5 Matrix{Int64}:
  6   7   8   9  10
 11  12  13  14  15

julia> vcat(a,b)
3×5 Matrix{Int64}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

julia> c = ([1 2 3], [4 5 6])
([1 2 3], [4 5 6])

julia> vcat(c...)
2×3 Matrix{Int64}:
 1  2  3
 4  5  6
```


## DataFrames

In [96]:
using DataFrames

In [98]:
#we can create a dataframe from plenty of things, lets start with dictionary
df = DataFrame(A = 1:4, B = ["A","B", "c", "D" ])

4×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     1  A
   2 │     2  B
   3 │     3  c
   4 │     4  D

In [102]:
df.A #to access any column directly or use df[!, :col]
df[!, :A] # this does not make a copy so any changes will be reflected

4-element Vector{Int64}:
 1
 2
 3
 4

In [104]:
df[:, :A][1] = 5 #see this doesnt change anything creating a copy

5

In [106]:
df[!, :A][1] = 5

5

In [107]:
df

4×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     5  A
   2 │     2  B
   3 │     3  c
   4 │     4  D

In [108]:
size(df)


(4, 2)

In [110]:
#in case we want to start with nothing 
df1 = DataFrame(A= Int[], B=  String[])
push!(df1, [1, "m"]) #can push tuple or vectors

1×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     1  m

In [112]:
df

5×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     5  A
   2 │     2  B
   3 │     3  c
   4 │     4  D
   5 │     1  m

In [111]:
#we describe
describe(df)

2×7 DataFrame
 Row │ variable  mean    min  median  max  nmissing  eltype   
     │ Symbol    Union…  Any  Union…  Any  Int64     DataType 
─────┼────────────────────────────────────────────────────────
   1 │ A         3.0     1    3.0     5           0  Int64
   2 │ B                 A            m           0  String

In [118]:
A = 1:3:100 #similar to np.arrange()

1:3:100

In [119]:
for i in A
    println(i)
end

1
4
7
10
13
16
19
22
25
28
31
34
37
40
43
46
49
52
55
58
61
64
67
70
73
76
79
82
85
88
91
94
97
100


In [120]:
#NA or null values are represented by the object `missing` 
a = [1 , 2 , missing]

3-element Vector{Union{Missing, Int64}}:
 1
 2
  missing

In [121]:
# now we can use an iterator skipmissing to perform operations
skipmissing(a)

skipmissing(Union{Missing, Int64}[1, 2, missing])

In [122]:
#we can sum the values of non missing characters 
sum(skipmissing(a))

3

In [123]:
collect(skipmissing(a))

2-element Vector{Int64}:
 1
 2

In [125]:
#to  replace the missing value we use (using broadcasting)
coalesce.(a, 0)

3-element Vector{Int64}:
 1
 2
 0

In [126]:
#for example we have a database with missing values in it
df1 = DataFrame(a = 1:5,x = [missing, 4, missing, 2, 1], y= y = [missing, missing, "c", "d", "e"])


5×3 DataFrame
 Row │ a      x        y       
     │ Int64  Int64?   String? 
─────┼─────────────────────────
   1 │     1  missing  missing 
   2 │     2        4  missing 
   3 │     3  missing  c
   4 │     4        2  d
   5 │     5        1  e

In [130]:
#similar to dropna we have 
dropmissing(df1) #drops every row including missing
# or use specific cols to drop
dropmissing(df1, [:x])

3×3 DataFrame
 Row │ a      x      y       
     │ Int64  Int64  String? 
─────┼───────────────────────
   1 │     2      4  missing 
   2 │     4      2  d
   3 │     5      1  e

In [131]:
# we need to install missings to use more features 
Pkg.add("Missings")

   Resolving package versions...
    Updating `C:\Users\Nihal\.julia\environments\v1.6\Project.toml`
  [e1d29d7a] + Missings v0.4.5
  No Changes to `C:\Users\Nihal\.julia\environments\v1.6\Manifest.toml`


In [137]:
#now we have more features from missing and replace na type
collect(Missings.replace(x, 1)) # collect is used to return an array of all items in iterator or collection

5-element Vector{Float64}:
 0.06642303695533736
 0.9567533636029237
 0.646690981531646
 0.11248587118714015
 0.2760209506672211

In [135]:
df1

5×3 DataFrame
 Row │ a      x        y       
     │ Int64  Int64?   String? 
─────┼─────────────────────────
   1 │     1  missing  missing 
   2 │     2        4  missing 
   3 │     3  missing  c
   4 │     4        2  d
   5 │     5        1  e

In [138]:
#now we use some data 
using CSV

In [147]:
iris = (CSV.read("C:\\Users\\Nihal\\Brand_Amul.csv", DataFrame))

387×29 DataFrame
 Row │ Column1  Subbrand                       Month       Sales      PCV      ⋯
     │ Int64    String                         Date…       Float64    Float64  ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │       0  HORLICKS LITE                  2015-09-01   5062.1    23.6     ⋯
   2 │       1  WOMENS HORLICKS                2015-09-01  24768.0    30.4
   3 │       2  HORLICKS HEALTH AND NUTRITION  2015-09-01  41876.0    43.0
   4 │       3  BOOST HEALTH AND ENERGY        2015-09-01   4404.3    11.1
   5 │       4  BOOST SPORTS                   2015-09-01   4386.6    19.9     ⋯
   6 │       5  BOURNVITA PROHEALTH            2015-09-01  21819.7    31.9
   7 │       6  COMPLAN ROYALE CHOCOLATE       2015-09-01   1211.4     4.7
   8 │       7  AMUL PRO WHEY                  2015-09-01    366.3     3.9
   9 │       8  MILO ACTIVE GO                 2015-09-01   5137.2    19.1     ⋯
  10 │       9  HORLICKS LITE                  2015-10-01   4429.3    25.2
  11 │      10  WOMENS HORLICKS                2015-10-01  24246.9    28.4
  ⋮  │    ⋮                   ⋮                    ⋮           ⋮         ⋮     ⋱
 378 │     377  MILO ACTIVE GO                 2019-02-01   2970.41   12.414
 379 │     378  HORLICKS LITE                  2019-03-01   7692.21   24.2744  ⋯
 380 │     379  WOMENS HORLICKS                2019-03-01  28557.5    37.6499
 381 │     380  HORLICKS HEALTH AND NUTRITION  2019-03-01  51132.4    39.8348
 382 │     381  BOOST HEALTH AND ENERGY        2019-03-01   2873.38   13.2678
 383 │     382  BOOST SPORTS                   2019-03-01   4702.93   19.1949  ⋯
 384 │     383  BOURNVITA PROHEALTH            2019-03-01  23408.0    35.8579
 385 │     384  COMPLAN ROYALE CHOCOLATE       2019-03-01   2500.94    9.76141
 386 │     385  AMUL PRO WHEY                  2019-03-01    527.055   4.01812
 387 │     386  MILO ACTIVE GO                 2019-03-01   3372.12   14.3486  ⋯
                                                 24 columns and 366 rows omitted

In [ ]:
#use \\ for the path or it wont work

In [149]:
first(iris, 5)

5×29 DataFrame
 Row │ Column1  Subbrand                       Month       Sales    PCV      P ⋯
     │ Int64    String                         Date…       Float64  Float64  F ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │       0  HORLICKS LITE                  2015-09-01   5062.1     23.6  5 ⋯
   2 │       1  WOMENS HORLICKS                2015-09-01  24768.0     30.4  4
   3 │       2  HORLICKS HEALTH AND NUTRITION  2015-09-01  41876.0     43.0  4
   4 │       3  BOOST HEALTH AND ENERGY        2015-09-01   4404.3     11.1  3
   5 │       4  BOOST SPORTS                   2015-09-01   4386.6     19.9  3 ⋯
                                                              24 columns omitted